---
# defaults file for postgres-config

pg_config_database_name: "sample"

pg_config_assign_roles: SUPERUSER,CREATEDB,LOGIN

pg_config_username: "sample"
## password
## - echo "md5$(echo -n '<password><username>' | md5sum | awk '{print $1}')"
##   - e.g. echo "md5$(echo -n 'passwordsample' | md5sum | awk '{print $1}')"
pg_config_password: "md548a8241422389e72787d7476da970e1d"
