---
# tasks file for postgres-install
- name: install postgres
  dnf:
    name:
    - '@postgresql:12/server'
    - 'postgresql-contrib'
    state: present

- name: "Initialize Database"
  shell: "/usr/bin/postgresql-setup initdb"
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
- name: "change bind host"
  blockinfile:
    dest: /var/lib/pgsql/data/postgresql.conf
    block: |
      listen_addresses='*'

- name: "to Service"
  systemd:
    name: postgresql
    enabled: yes
- name: "start service"
  systemd:
    name: postgresql
    state: started
